import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Fleur_De_Leah, Smooch_Sans, Playfair_Display } from "next/font/google";

const fleur = Fleur_De_Leah({ 
  weight: '400',
  subsets: ["latin"],
  variable: '--font-fleur', 
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: '--font-playfair',
});

const smoochSans = Smooch_Sans({
  weight: '200',
  subsets: ["latin"],
  variable: '--font-smooch-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fleur.variable} ${smoochSans.variable} ${playfair.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}

