import type { Metadata } from "next";
import Link from 'next/link'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Fleur_De_Leah, Smooch_Sans, Playfair_Display } from "next/font/google";

const fleur = Fleur_De_Leah({ 
  weight: '400',
  subsets: ["latin"],
  variable: '--font-fleur', 
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: '--font-playfair',
});

const smoochSans = Smooch_Sans({
  weight: '200',
  subsets: ["latin"],
  variable: '--font-smooch-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${fleur.variable} ${smoochSans.variable} ${playfair.variable}`}>
      <body className="bg-[#FDF5E6]antialiased">
        <nav className="max-w-10xl px-10 py-6 flex justify-between items-center font-serif bg-[#faf7f2] text-[#556B2F]">
          <Link href="/" className="text-xl font-bold hover:text-[#C87D87]">Asiyah Shaikh</Link>
          <div className="flex gap-6 text-[#6B4E31]">
            <Link href="/" className="hover:text-[#C87D87]">Home</Link>
            <Link href="/about" className="hover:text-[#C87D87]">About & Contact</Link>
            <Link href="/projects" className="hover:text-[#C87D87]">Projects</Link>
            <Link href="/skills" className="hover:text-[#C87D87]">Skills</Link>
          </div>
        </nav>
        {children}
        </body>
    </html>
  );
}